DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS visits;

# USERS TABLE
CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255),
  password VARCHAR(100),
  firstName VARCHAR(30),
  lastName VARCHAR(30)
);


# LOCATIONS TABLE

CREATE TABLE locations (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(85),
  country VARCHAR(50),
  latitude DECIMAL(8,6),
  longitude DECIMAL(9,6)
);

# VISITS TABLE

CREATE TABLE visits (
  id INT PRIMARY KEY AUTO_INCREMENT,
  userId INT,
  locationId INT,
  didVisit BOOLEAN
);